spring:
  application:
    name: product-order-api
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:product_order}
    password: ${RABBITMQ_PASSWORD:product_order}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081/realms/product-order}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8081/realms/product-order/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  security:
    audience: ${JWT_AUDIENCE:product-order-api}
  idempotency:
    ttl: ${IDEMPOTENCY_TTL:PT24H}
  payment:
    fake:
      decline: ${FAKE_PAYMENT_DECLINE:false}
  rabbitmq:
    payment-exchange: ${PAYMENT_EXCHANGE:ecommerce.payment.exchange}
    payment-requested-queue: ${PAYMENT_REQUESTED_QUEUE:payment.requested.queue}
    payment-requested-routing-key: ${PAYMENT_REQUESTED_ROUTING_KEY:payment.requested}
    payment-delay-queue: ${PAYMENT_DELAY_QUEUE:payment.requested.delay.queue}
    payment-delay-routing-key: ${PAYMENT_DELAY_ROUTING_KEY:payment.requested.delay}
    payment-delay-ms: ${PAYMENT_DELAY_MS:30000}
    payment-requested-dlq: ${PAYMENT_REQUESTED_DLQ:payment.requested.dlq}
    payment-requested-dlq-routing-key: ${PAYMENT_REQUESTED_DLQ_ROUTING_KEY:payment.requested.dlq}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
