ALTER TABLE orders DROP CONSTRAINT chk_orders_status;

UPDATE orders
SET status = CASE status
    WHEN 'PENDING' THEN 'CREATED'
    WHEN 'CANCELLED' THEN 'DECLINED'
    ELSE status
END;

ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'CREATED';

ALTER TABLE orders
    ADD CONSTRAINT chk_orders_status CHECK (status IN ('CREATED', 'PROCESSING', 'CONFIRMED', 'DECLINED'));
